### ISSUE TITLE
url with trailing cash are not being cached

### ISSUE THREAD

**Issue by wkhayrattee** [pressjitsu/pj-page-cache-red#30] opened 2020-05-18 12:44 UTC
Hello,
let's take for example the url (article post) `https://domain.com/hello-world`

1) for `https://domain.com/hello-world`, **x-pj-cache-status: hit**

2) for `https://domain.com/hello-world/`, **x-pj-cache-status: miss**

why is that

**Comment by soulseekah** [comment] 2020-05-18 14:43
`hello-world` shouldn't even be a thing. WordPress has a canonical redirect to `hello-world/`, we would cache the redirect (only 5xx codes are not cached) immediately.
Otherwise we make no assumptions, we can't cache it under the same key as that's literally a different URI.

**Comment by wkhayrattee** [comment] 2020-05-19 06:02
ok.. thank you for this info.
Apart from the headers, how can I make sure the caching is working?

I have installed two instances, one with both the pj object cache and pj page cache
I can't see big difference compared with the instance without any cache..

**Comment by soulseekah** [comment] 2020-05-19 06:45
How are you measuring this difference, @7php?

**Comment by wkhayrattee** [comment] 2020-05-19 06:52
using developer tools from firefox

**Comment by soulseekah** [comment] 2020-05-19 06:52
And what are the results? Are you looking at TTFB?

**Comment by soulseekah** [comment] 2020-05-19 06:55
I think it's an issue with your setup in some way and not a bug with the plugin.

I invite you to hire me or any other Codeable professional to help you solve your speed issu sites https://app.codeable.io/tasks/new?preferredContractor=76831

Closing this issue for now. Thanks.

**Closed as completed by soulseekah** 2020-05-19 06:55 UTC

**Comment by wkhayrattee** [comment] 2020-05-19 07:56
That's fine, I can manage. 
I was just asking for thoughts.

Though, thank you for the service, I'll keep that in mind

**Comment by wkhayrattee** [comment] 2020-05-20 12:14
@soulseekah I found the issue..
actually when I logged-in or add a product to cart, woocommerce generates a session.
and because the session cookie is there, the caching does not work..

if I flush the browser cache, then it works..

it makes sense
